export CACHE_LIST="['localhost:4000', 'localhost:4000', 'localhost:4000', 'localhost:4000', 'localhost:4000', 'localhost:4000', 'localhost:4000', 'localhost:4000']"
export WEB_HOST="localhost"
export WEB_PORT="5000"
export IMAGE_STORAGE_HOST="localhost"
export IMAGE_STORAGE_PORT="5001"
export AUTO_SCALER_HOST="localhost"
export AUTO_SCALER_PORT="5002"
export MANAGER_HOST="localhost"
export MANAGER_PORT="5003"
export IMAGE_DIRECTORY="D:/ImagesForECE1779"
export RDS_HOST="ece1779a2.cvf3ue1iuurv.us-east-1.rds.amazonaws.com"
export RDS_USER="root"
export RDS_PASSWORD="password"
export RDS_DATABASE="ece1779a2"
export BUCKET_NAME="ece1779-a2-bucket"
python3 run_autoscaler.py & python3 run_storageapp.py & python3 run_managerapp.py & python3 run_webapp.py &
